[general]
enabled=yes
bindaddr=0.0.0.0
port=5038

[aibots]
secret=AIBOTS_AMI_SECRET
deny=0.0.0.0/0.0.0.0
permit=127.0.0.1/255.255.255.255
permit=172.16.0.0/255.240.0.0
permit=10.0.0.0/255.0.0.0
read=system,call,log,verbose,agent,user,config,dtmf,reporting,cdr,dialplan
write=system,call,agent,originate,reporting
