"""Sync Asterisk IP-based identify file from Vicidial server list."""
from __future__ import annotations

import logging
import os
import shutil
import socket
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import get_settings
from app.models import VicidialServer

logger = logging.getLogger(__name__)
settings = get_settings()

IDENTIFY_PATH = Path(os.getenv("ASTERISK_IDENTIFY_PATH", "/data/asterisk/pjsip_identify.conf"))
ALLOWED_IPS_PATH = Path(os.getenv("ASTERISK_ALLOWED_IPS_PATH", "/data/asterisk/allowed_ips.txt"))


def _peer_ip(row: VicidialServer) -> str:
    return (row.sip_ip or row.host or "").strip()


def _safe_write_text(path: Path, content: str) -> None:
    """
    Write text file safely.
    Docker sometimes creates a DIRECTORY at the bind-mount path if the file
    was missing on first `compose up` — fix that and rewrite as a file.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.is_dir():
        logger.warning("Removing accidental directory at %s (Docker bind-mount glitch)", path)
        shutil.rmtree(path)
    # Atomic-ish write
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)


def _write_allowed_ips(ips: list[str]) -> None:
    """One IPv4 per line — consumed by aibots-firewall container."""
    body = "\n".join(ips) + ("\n" if ips else "")
    _safe_write_text(
        ALLOWED_IPS_PATH,
        "# Auto-generated from Portal → VICIdial Servers\n"
        "# Only these IPs may hit Asterisk SIP/RTP (firewall sync)\n"
        + body,
    )
    logger.info("Wrote %s (%s IP(s))", ALLOWED_IPS_PATH, len(ips))


def _ami_reload_pjsip() -> bool:
    """Reload PJSIP via AMI on aibots-asterisk (no docker CLI needed)."""
    host = os.getenv("ASTERISK_AMI_RELOAD_HOST", "asterisk")
    port = int(os.getenv("ASTERISK_AMI_PORT", "5038"))
    user = os.getenv("ASTERISK_AMI_USER", settings.asterisk_ami_user)
    secret = os.getenv("ASTERISK_AMI_SECRET", settings.asterisk_ami_secret)
    try:
        with socket.create_connection((host, port), timeout=3) as sock:
            sock.settimeout(3)
            sock.recv(1024)
            sock.sendall(
                f"Action: Login\r\nUsername: {user}\r\nSecret: {secret}\r\n\r\n".encode()
            )
            sock.recv(4096)
            sock.sendall(b"Action: Command\r\nCommand: module reload res_pjsip.so\r\n\r\n")
            sock.recv(4096)
            sock.sendall(b"Action: Logoff\r\n\r\n")
            return True
    except Exception as exc:
        logger.warning("AMI PJSIP reload failed: %s", exc)
        return False


async def rebuild_asterisk_identify(db: AsyncSession) -> str:
    """
    Write pjsip_identify.conf with match= lines for every active Vicidial IP.
    No SIP registration — source-IP identification only.
    """
    rows = (
        await db.execute(
            select(VicidialServer).where(VicidialServer.active == True).order_by(VicidialServer.id.asc())  # noqa: E712
        )
    ).scalars().all()

    ips: list[str] = []
    for r in rows:
        ip = _peer_ip(r)
        if ip and ip not in ips:
            ips.append(ip)

    if not ips:
        seed = os.getenv("ASTERISK_AMI_HOST") or os.getenv("VICIDIAL_IP") or ""
        if seed and seed not in ("127.0.0.1", "YOUR_VICIDIAL_IP"):
            ips.append(seed)

    lines = [
        "; Auto-generated by AIBOTS portal — DO NOT EDIT BY HAND",
        "; IP-based VICIdial peers (no SIP registration)",
        ";",
        "; Catch-all: any INVITE that reaches Asterisk maps to [vicidial].",
        "; Security is the host firewall (allowed_ips.txt), not PJSIP identify.",
        "; (Wrong/private SIP IP in portal used to silently drop real Vicibox traffic.)",
        "[vicidial-identify]",
        "type=identify",
        "endpoint=vicidial",
        "match=0.0.0.0/0",
    ]
    for ip in ips:
        lines.append(f"; portal server: {ip}")

    content = "\n".join(lines) + "\n"
    try:
        _safe_write_text(IDENTIFY_PATH, content)
        logger.info("Wrote %s with %s IP(s)", IDENTIFY_PATH, len(ips))
        _write_allowed_ips(ips)
    except Exception as exc:
        # Never fail the portal CRUD because of filesystem/AMI issues
        logger.exception("Asterisk identify/firewall file sync failed: %s", exc)
        return f"ERROR: {exc}\n{content}"

    if _ami_reload_pjsip():
        logger.info("PJSIP reloaded via AMI")
    else:
        logger.info("Identify file written — restart asterisk if calls fail: docker compose restart asterisk")

    return content


def vicidial_ip_peer_snippet(aibots_public_ip: str, peer_name: str = "aibots") -> str:
    """chan_sip peer text for Vicidial Asterisk — IP trunk, no register, no auth."""
    return (
        f"; AIBOTS IP trunk — paste into Vicibox sip.conf / sip-vicidial.conf\n"
        f"; CRITICAL: do NOT set username= or secret= (causes Failed to authenticate / CONGESTION)\n"
        f"[{peer_name}]\n"
        f"host={aibots_public_ip}\n"
        f"type=peer\n"
        f"context=trunkinbound\n"
        f"disallow=all\n"
        f"allow=ulaw\n"
        f"insecure=port,invite\n"
        f"nat=force_rport,comedia\n"
        f"qualify=yes\n"
        f"qualifyfreq=60\n"
        f"; NO username / secret / fromuser / register =>\n"
    )
