"""Sync Asterisk IP-based identify file from Vicidial server list."""
from __future__ import annotations

import logging
import os
import socket
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import get_settings
from app.models import VicidialServer

logger = logging.getLogger(__name__)
settings = get_settings()

IDENTIFY_PATH = Path(os.getenv("ASTERISK_IDENTIFY_PATH", "/data/asterisk/pjsip_identify.conf"))
ALLOWED_IPS_PATH = Path(os.getenv("ASTERISK_ALLOWED_IPS_PATH", "/data/asterisk/allowed_ips.txt"))


def _peer_ip(row: VicidialServer) -> str:
    return (row.sip_ip or row.host or "").strip()


def _write_allowed_ips(ips: list[str]) -> None:
    """One IPv4 per line — consumed by aibots-firewall container."""
    ALLOWED_IPS_PATH.parent.mkdir(parents=True, exist_ok=True)
    body = "\n".join(ips) + ("\n" if ips else "")
    ALLOWED_IPS_PATH.write_text(
        "# Auto-generated from Portal → VICIdial Servers\n"
        "# Only these IPs may hit Asterisk SIP/RTP (firewall sync)\n"
        + body,
        encoding="utf-8",
    )
    logger.info("Wrote %s (%s IP(s))", ALLOWED_IPS_PATH, len(ips))


def _ami_reload_pjsip() -> bool:
    """Reload PJSIP via AMI on aibots-asterisk (no docker CLI needed)."""
    host = os.getenv("ASTERISK_AMI_RELOAD_HOST", "asterisk")
    port = int(os.getenv("ASTERISK_AMI_PORT", "5038"))
    user = os.getenv("ASTERISK_AMI_USER", settings.asterisk_ami_user)
    secret = os.getenv("ASTERISK_AMI_SECRET", settings.asterisk_ami_secret)
    try:
        with socket.create_connection((host, port), timeout=3) as sock:
            sock.settimeout(3)
            sock.recv(1024)
            sock.sendall(
                f"Action: Login\r\nUsername: {user}\r\nSecret: {secret}\r\n\r\n".encode()
            )
            sock.recv(4096)
            sock.sendall(b"Action: Command\r\nCommand: module reload res_pjsip.so\r\n\r\n")
            sock.recv(4096)
            sock.sendall(b"Action: Logoff\r\n\r\n")
            return True
    except Exception as exc:
        logger.warning("AMI PJSIP reload failed: %s", exc)
        return False


async def rebuild_asterisk_identify(db: AsyncSession) -> str:
    """
    Write pjsip_identify.conf with match= lines for every active Vicidial IP.
    No SIP registration — source-IP identification only.
    """
    rows = (
        await db.execute(
            select(VicidialServer).where(VicidialServer.active == True).order_by(VicidialServer.id.asc())  # noqa: E712
        )
    ).scalars().all()

    ips: list[str] = []
    for r in rows:
        ip = _peer_ip(r)
        if ip and ip not in ips:
            ips.append(ip)

    if not ips:
        seed = os.getenv("ASTERISK_AMI_HOST") or os.getenv("VICIDIAL_IP") or ""
        if seed and seed not in ("127.0.0.1", "YOUR_VICIDIAL_IP"):
            ips.append(seed)

    lines = [
        "; Auto-generated by AIBOTS portal — DO NOT EDIT BY HAND",
        "; IP-based VICIdial peers (no SIP registration)",
        "[vicidial-identify]",
        "type=identify",
        "endpoint=vicidial",
    ]
    for ip in ips:
        lines.append(f"match={ip}")
    if not ips:
        lines.append("; (no Vicidial servers yet — add them in Portal → VICIdial Servers)")

    content = "\n".join(lines) + "\n"
    IDENTIFY_PATH.parent.mkdir(parents=True, exist_ok=True)
    IDENTIFY_PATH.write_text(content, encoding="utf-8")
    logger.info("Wrote %s with %s IP(s)", IDENTIFY_PATH, len(ips))

    _write_allowed_ips(ips)

    if _ami_reload_pjsip():
        logger.info("PJSIP reloaded via AMI")
    else:
        logger.info("Identify file written — restart asterisk if calls fail: docker compose restart asterisk")

    return content


def vicidial_ip_peer_snippet(aibots_public_ip: str, peer_name: str = "aibots") -> str:
    """chan_sip peer text for Vicidial Asterisk — IP trunk, no register."""
    return (
        f"[{peer_name}]\n"
        f"host={aibots_public_ip}\n"
        f"type=peer\n"
        f"context=trunkinbound\n"
        f"disallow=all\n"
        f"allow=ulaw\n"
        f"insecure=port,invite\n"
        f"nat=force_rport,comedia\n"
        f"; NO register => line — IP-based only\n"
    )
